apiVersion: v1
kind: Service
metadata:
  name: kuberay-training-head-svc
  namespace: ray
  labels:
    app: kuberay-training
spec:
  type: ClusterIP
  selector:
    app: kuberay-training
    ray.io/node-type: head
  ports:
    - name: metrics
      port: 8002
      targetPort: 8002
    - name: dashboard
      port: 8265
      targetPort: 8265
