apiVersion: v1
kind: Service
metadata:
  name: kuberay-training-metrics-svc
  namespace: ray
  labels:
    app: kuberay-training
    component: submitter-metrics
spec:
  type: ClusterIP
  selector:
    job-name: kuberay-job
  ports:
    - name: metrics
      port: 8002
      targetPort: 8002
