backendStore:
  databaseMigration: true
  postgres:
    enabled: true
    host: postgres-postgresql
    port: 5432
    database: mlflow
    user: postgres
    password: postgres

artifactRoot:
  s3:
    enabled: true
    bucket: k8s-mlops-platform-bucket
    path: mlflow-artifacts

extraEnvVars:
  MLFLOW_S3_IGNORE_TLS: "true"
  MLFLOW_SERVER_ALLOWED_HOSTS: "my-mlflow,my-mlflow.ray,my-mlflow.ray.svc,my-mlflow.ray.svc.cluster.local,localhost:*,mlflow.localhost,mlflow"
  MLFLOW_WEBHOOK_ALLOWED_SCHEMES: "http,https"
  MLFLOW_WEBHOOK_SECRET_ENCRYPTION_KEY: "BKOaxFUmdRaDTseWeacCpPQqYbdjrUrs7UJkRamleWM="

extraSecretNamesForEnvFrom:
  - env-secret
